[build-system]
requires = ["setuptools>=62.0.0"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
skip_gitignore = true
single_line_exclusions = ["typing"]

[tool.black]
line_length = 120
